//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public int Id { get; set; }
        public Nullable<int> customerId { get; set; }
        public Nullable<int> petId { get; set; }
        public Nullable<System.DateTime> dateOfSale { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual pet pet { get; set; }
    }
}
