//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class soldPet
    {
        public int Id { get; set; }
        public Nullable<int> categoryId { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public Nullable<bool> gender { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual category category { get; set; }
    }
}
