//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIHHospital.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContextClass1 : DbContext
    {
        public ContextClass1()
            : base("name=ContextClass1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Appointment> Appointments { get; set; }
        public DbSet<Doctor> Doctors { get; set; }
        public DbSet<Emergency_Contact> Emergency_Contacts { get; set; }
        public DbSet<Patient> Patients { get; set; }
        public DbSet<Appointment1> Appointment1 { get; set; }
        public DbSet<Contact> Contacts { get; set; }
    }
}
