//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectRevised.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.orders = new HashSet<order>();
            this.paymentInfoes = new HashSet<paymentInfo>();
        }
    
        public int Id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string address { get; set; }
        public string phoneNo { get; set; }
        public string email { get; set; }
        public string passwrd { get; set; }
    
        public virtual ICollection<order> orders { get; set; }
        public virtual ICollection<paymentInfo> paymentInfoes { get; set; }
    }
}
