//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectRevised.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContextClass : DbContext
    {
        public ContextClass()
            : base("name=ContextClass")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<category> categories { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<order> orders { get; set; }
        public DbSet<orderItem> orderItems { get; set; }
        public DbSet<paymentInfo> paymentInfoes { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<rating> ratings { get; set; }
    }
}
