//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectRevised.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderItem
    {
        public int Id { get; set; }
        public Nullable<int> orderId { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<int> qty { get; set; }
    
        public virtual order order { get; set; }
        public virtual product product { get; set; }
    }
}
