//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectRevised.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public order()
        {
            this.orderItems = new HashSet<orderItem>();
        }
    
        public int Id { get; set; }
        public Nullable<int> custId { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> paymentInfo { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual paymentInfo paymentInfo1 { get; set; }
        public virtual ICollection<orderItem> orderItems { get; set; }
    }
}
