//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectRevised.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.orderItems = new HashSet<orderItem>();
            this.ratings = new HashSet<rating>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public Nullable<int> qty { get; set; }
        public string desc { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> categoryId { get; set; }
    
        public virtual category category { get; set; }
        public virtual ICollection<orderItem> orderItems { get; set; }
        public virtual ICollection<rating> ratings { get; set; }
    }
}
