//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectRevised.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rating
    {
        public int Id { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<int> C1_star { get; set; }
        public Nullable<int> C2_star { get; set; }
        public Nullable<int> C3_star { get; set; }
        public Nullable<int> C4_star { get; set; }
        public Nullable<int> C5_star { get; set; }
    
        public virtual product product { get; set; }
    }
}
