//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab7_Revised_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sold_Pet
    {
        public int Id { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string Gender { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Sold_Pet(int id, int? categoryid, DateTime? birthdate, string gender, decimal? price)
        {
            Id = id;
            Category_Id = categoryid;
            Birthdate = birthdate;
            Gender = gender;
            Price = price;
        }
        public Sold_Pet() { }
    }
}
